In [11]:
import pandas as pd
df = pd.read_csv('data/score.csv')
df

  Unnamed: 0   이름   학교    키   국어   영어   수학  과학  사회        SW특기
0         1번  채치수  북산고  197   90   85  100  95  85      Python
1         2번  정대만  북산고  184   40   35   50  55  25        Java
2         3번  송태섭  북산고  168   80   75   70  80  75  Javascript
3         4번  서태웅  북산고  187   40   60   70  75  80         NaN
4         5번  강백호  북산고  188   15   20   10  35  10         NaN
5         6번  변덕규  능남고  202   80  100   95  85  80           C
6         7번  황태산  능남고  188   55   65   45  40  35      PYTHON
7         8번  윤대협  능남고  190  100   85   90  95  95          C#

In [5]:
data = {
    '이름' : ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교' : ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키' : [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']
}

In [6]:
df = pd.DataFrame(data, index=['1번', '2번', '3번', '4번','5번', '6번', '7번', '8번'])
df

     이름   학교    키   국어   영어   수학  과학  사회        SW특기
1번  채치수  북산고  197   90   85  100  95  85      Python
2번  정대만  북산고  184   40   35   50  55  25        Java
3번  송태섭  북산고  168   80   75   70  80  75  Javascript
4번  서태웅  북산고  187   40   60   70  75  80
5번  강백호  북산고  188   15   20   10  35  10
6번  변덕규  능남고  202   80  100   95  85  80           C
7번  황태산  능남고  188   55   65   45  40  35      PYTHON
8번  윤대협  능남고  190  100   85   90  95  95          C#

In [7]:
df['이름']

1번    채치수
2번    정대만
3번    송태섭
4번    서태웅
5번    강백호
6번    변덕규
7번    황태산
8번    윤대협
Name: 이름, dtype: object

In [13]:
df[cols[-1]]

NameError: name 'cols' is not defined

TypeError: cannot do slice indexing on RangeIndex with these indexers [5번] of type str